define([],
[
	{path:"baiduMapDemo/index",name:"百度地图"},
	{path:"lsLoaderDemo/index",name:"页面本地化"},
	{path:"prLoaderDemo/index",name:"页面预加载"},
	//{path:"hybridDemo/index",name:"混合开发"},
	{path:"normalPageDemo/index",name:"一般页面开发"},
	{path:"naviPageDemo/index",name:"具有导航栏页面开发"},
	{path:"viewDemo/index",name:"view开发"},
	{path:"remDemo/index",name:"rem页面适配"},
	{path:"pageJumpDemo/index",name:"页面跳转效果"},
	{path:"pageJumpParamsDemo/index",name:"页面跳转参数传递和多级返回功能"},
	{path:"netDemo/index",name:"网络API开发"},
	{path:"netLocalDemo/index",name:"网络本地数据框架"},
	{path:"cacheDemo/index",name:"网络缓存"},
	{path:"sendCheckDemo/index",name:"网络请求发送策略"},
	{path:"datePickerDemo/index",name:"日期选择器 DatePickerView"},
	{path:"selectDemo/index",name:"选项选择器 SelectView"},
	{path:"switchDemo/index",name:"开关 Switch"},
	{path:"refreshViewDemo/index",name:"下拉刷新 RefreshView"},
	{path:"refreshListViewDemo/index",name:"列表刷新 ListView"},	
	{path:"alertDemo/index",name:"Alert AlertView"},
	{path:"indicatorDemo/index",name:"指示器 IndicatorView"},
	{path:"statusDemo/index",name:"消息提示 StatusView"},
	{path:"tabBarDemo/index",name:"tab栏 TabBarView"},
	{path:"swipeDemo/index",name:"滑动页 SwipeView"},
	{path:"tabDemo/index",name:"tab页 TabView"},
	{path:"lazyLoadDemo/index", name:"图片延迟加载"},
	{path:"lazyLoadListDemo/index", name:"图片延迟加载 List应用"},
	{path:"tabComplexDemo/index",name:"Complex Tab"},
	{path:"IOAnimCallbackDemo/index", name:"过场动画回调"},
	{path:"dataCenterDemo/index", name:"数据中心"},
]);