module.exports = 
{
	dest:"dest",
    useWindowLoading : true,
	lsCaches:
	{
        //all:true,
    	dirs:
    	[
            // directory or files
            "alertDemo",
            "application",
            "baiduMapDemo",
            "cacheDemo",
            "common",
            "dataCenterDemo",
            "datePickerDemo",
            "hybridDemo",
            "indicatorDemo",
            "IOAnimCallbackDemo",
            "lazyLoadDemo",
            "lazyLoadListDemo",
            "lsLoaderDemo",
            "naviPageDemo",
            "netDemo",
            "netLocalDemo",
            "normalPageDemo",
            "pageJumpDemo",
            "pageJumpParamsDemo",
            "prLoaderDemo",
            "refreshListViewDemo",
            "refreshViewDemo",
            "remDemo",
            "sendCheckDemo",
            "statusDemo",
            "swipeDemo",
            "switchDemo",
            "tabBarDemo",
            "tabDemo",
            "scrollViewDemo",
            "lazyLoadViewDemo",
            "viewDemo",
            "welcome",
            "selectDemo",
    	],
	},
    webIndexes:
    {
        //css:"app/css/app.css",
        files:
        [
            {
                name:"index.html",
                inlines:
                [
                    //"home/index",
                ]
            }
            
        ]
    }
}