module.exports = 
{
	dest:"dest",
    useWindowLoading : true,
	lsCaches:
	{
        //all:true,
    	dirs:
    	[
            // directory or files
            "alertDemo",
            "application",
            "baiduMapDemo",
            "cacheDemo",
            "common",
            "dataCenterDemo",
            "datePickerDemo",
            "hybridDemo",
            "indicatorDemo",
            "IOAnimCallbackDemo",
            "lazyLoadDemo",
            "lazyLoadListDemo",
            "lsLoaderDemo",
            "naviPageDemo",
            "netDemo",
            "netLocalDemo",
            "normalPageDemo",
            "pageJumpDemo",
            "pageJumpParamsDemo",
            "prLoaderDemo",
            "refreshListViewDemo",
            "refreshViewDemo",
            "remDemo",
            "sendCheckDemo",
            "statusDemo",
            "swipeDemo",
            "switchDemo",
            "tabBarDemo",
            "viewDemo",
            "welcome",
            "selectDemo",
    	],
	}
}